# Generated by Django 5.1.2 on 2024-11-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resumeentry",
            name="end",
            field=models.DateField(blank=True, null=True),
        ),
    ]
