# Generated by Django 5.2.11 on 2026-03-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_resumeentry_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='bluesky_link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='art',
            name='mastodon_link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='bluesky_link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='mastodon_link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='bluesky_link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='mastodon_link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
